name: LF Oracle Production Deploy

on:
  workflow_dispatch:
    inputs:
      services:
        description: Space separated list of services to deploy
        required: true

env:
  CLOUD_ENV: lf-oracle-production
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  ORACLE_USER: ${{ secrets.ORACLE_USER }}
  ORACLE_TENANT: ${{ secrets.ORACLE_TENANT }}
  ORACLE_REGION: ${{ secrets.ORACLE_REGION }}
  ORACLE_FINGERPRINT: ${{ secrets.ORACLE_FINGERPRINT }}
  ORACLE_KEY: ${{ secrets.ORACLE_KEY }}
  ORACLE_CLUSTER: ${{ secrets.ORACLE_CLUSTER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node/builder
        with:
          services: ${{ github.event.inputs.services }}
