name: Staging Deploy Backend services

on:
  push:
    branches:
      - "staging/**"
      - "staging-**"
    paths:
      - "backend/**"
      - "services/libs/**"
      - "!backend/src/serverless/microservices/python/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  CROWD_CLUSTER: ${{ secrets.STAGING_CLUSTER_NAME }}
  CROWD_ROLE_ARN: ${{ secrets.STAGING_CLUSTER_ROLE_ARN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SLACK_CHANNEL: deploys-staging
  SLACK_WEBHOOK: ${{ secrets.STAGING_SLACK_CHANNEL_HOOK }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.IMAGE }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-docker-image
        id: image-builder
        with:
          image: backend

      - name: Set docker image output
        id: image
        run: echo "IMAGE=${{ steps.image-builder.outputs.image }}" >> $GITHUB_OUTPUT

  deploy-api:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: api
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}

  deploy-nodejs-worker:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: nodejs-worker
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}
          prioritized: true
          only_normal_queue_level: true

  deploy-job-generator:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: job-generator
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}

  deploy-discord-ws:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: discord-ws
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}
