name: Staging Deploy Backend services

on:
  push:
    branches:
      - 'staging/**'
      - 'feature/ci-cd-staging-C-196'
    paths:
      - 'backend/**'
      - '!backend/src/serverless/microservices/python/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  CROWD_CLUSTER: ${{ secrets.STAGING_CLUSTER_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.IMAGE }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-docker-image
        id: image-builder
        with:
          image: backend

      - name: Set docker image output
        id: image
        run: echo "IMAGE=${{ steps.image-builder.outputs.image }}" >> $GITHUB_OUTPUT

  deploy-api:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: api
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}

  deploy-nodejs-worker:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: nodejs-worker
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}

  deploy-job-generator:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy-service
        with:
          service: job-generator
          image: ${{ needs.build-and-push.outputs.image }}
          cluster: ${{ env.CROWD_CLUSTER }}
